apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: test-mlflow-image
  generateName: test-mlflow-image-tensorflow-housing-
spec:
  params:
  - name: model-name
    value: tensorflow-housing
  - name: model-version
    value: "1"
  - name: test-endpoint
    value: "v1/models/tensorflow-housing/versions/1:predict"
  - name: target-namespace
    value: $(context.pipelineRun.namespace)
  pipelineRef:
    name: test-mlflow-image
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: workspace
  - configMap:
      name: tensorflow-housing-test-data
    name: test-data
