apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: test-mlflow-image
  generateName: test-mlflow-image-bike-rentals-
spec:
  params:
  - name: model-name
    value: bike-rentals-auto-ml
  - name: model-version
    value: "1"
  - name: test-endpoint
    value: "invocations"
  - name: target-namespace
    value: $(context.pipelineRun.namespace)
  pipelineRef:
    name: test-mlflow-image
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: workspace
  - configMap:
      name: bike-rentals-test-data
    name: test-data
