# Create the MLServer container.
# 
FROM docker.io/openvino/model_server:latest

USER root
RUN mkdir /models && chown ovms:ovms /models

USER ovms

# CHANGE THIS LINE TO MATCH YOUR MODEL
COPY --chown=ovms:ovms tensorflow-housing/tf2model /models/1
RUN rm -f /models/1/fingerprint.pb

# https://stackoverflow.com/a/41207910/19020549
# ENTRYPOINT ["/usr/bin/env"]

EXPOSE 9090 8080

CMD ["/ovms/bin/ovms", "--model_path", "/models", "--model_name", "tensorflow_housing", "--port", "9090", "--rest_port", "8080", "--shape", "auto"]