apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: azureml-container
  generateName: azureml-container-bike-share-
spec:
  params:
  - name: model-name
    value: bike-share-auto-ml
  - name: model-version
    value: "1"
  - name: azure-env-secret-name
    value: azure-env
  - name: aws-env-secret-name
    value: aws-env
  pipelineRef:
    name: azureml-container
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: ws
    persistentVolumeClaim:
      claimName: build-cache-pvc
  - name: docker
    persistentVolumeClaim:
      claimName: dockerfile-cache-pvc
