apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-model-exists
spec:
  description: This Task can be used to check if the model files are present
  params:
  - name: model-name
    type: string
  - name: current-namespace 
    default: "default"
    type: string
  steps:
  - name: check-model-files
    image: registry.access.redhat.com/ubi9/ubi
    script: ls -l $(params.model-name)/
    workingDir: $(workspaces.workspace.path)
  workspaces:
  - description: The workspace for the downloaded model.
    name: workspace