apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: download-containerfile
spec:
  description: This Task can be used to a download a Containerfile
  params:
  - name: model-name
    type: string
  - name: containerfile-url
    type: string
  - name: current-namespace 
    default: "default"
    type: string
  steps:
  - name: download-containerfile
    image: registry.access.redhat.com/ubi9/ubi
    script: curl -o Dockerfile $(params.containerfile-url)
    workingDir: $(workspaces.dockerfile.path) 
  workspaces:
  - description: The workspace for the dockerfile.
    name: dockerfile