kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- azureml-container-dockerfile-cache-pvc.yaml
- kserve-download-model.yaml
- check-model-exists.yaml
- azureml-container-pipeline.yaml
