# Download model from Amazon S3
FROM quay.io/opendatahub/kserve-storage-initializer:v0.11 as s3_downloader

USER root

# aws-storage-config is bound by running, e.g.: podman build --secret id=aws-storage-config,src=./aws-storage-config
# The file should have this contents (replace values):
#   { "type": "s3", "access_key_id": "$", "secret_access_key": "$", "endpoint_url": "$", "bucket": "example-models", "region": "us-west-1" }
RUN --mount=type=secret,id=aws-storage-config,target=/mnt/aws-storage-config,uid=1000 \
  STORAGE_CONFIG="$(cat /mnt/aws-storage-config)" /storage-initializer/scripts/initializer-entrypoint \
  's3://rhoai-edge-models/tensorflow-housing/python_env.yaml' \
  /home/test/

RUN cat /home/test/